package ezra.mit.navigation

const val ROUTE_LOGIN = "login"
const val ROUTE_SIGNUP = "signup"
const val ROUTE_HOME = "home"
const val ROUTE_ABOUT = "about"
const val ROUTE_SALE = "sale"
const val ROUTE_RENT = "rent"
const val ROUTE_RENTDETAILS = "rentdetails"
const val ROUTE_SALEDETAILS = "saledetails"
const val ROUTE_START = "start"
const val ROUTE_SPLASH = "spash"
const val ROUTE_HOMELOGIN = "homelogin"
const val ROUTE_Ren = "ren"
const val ROUTE_Ren2 = "renn"
const val ROUTE_Ren4 = "rennn"
const val ROUTE_Ren5 = "rennnn"
const val ROUTE_Ren6 = "rennnnn"
const val ROUTE_Ren7 = "rennnnnn"
const val ROUTE_Ren8 = "rennnnnnn"
const val ROUTE_Sell2 = "sell"
const val ROUTE_Sell3 = "selll"
const val ROUTE_Sell4 = "sellll"
const val ROUTE_Sell5 = "selllll"
const val ROUTE_Sell6 = "sellllll"
const val ROUTE_Sell7 = "selllllll"